package app.reup.sync

// GENERATED by reup/scripts/gen-store-vectors.ts from reup/schema.sql.
// Do not edit. Run `pnpm gen:store-vectors` in the desktop repo instead.
//
// The desktop reads that file directly. The phone gets it as a constant so
// that there is no asset to ship, no file to find at runtime, and no way for
// the two to disagree without this line changing in a commit.
//
// Pure ASCII on purpose: concatenated literals are still a compile-time
// constant, and no charset setting anywhere can alter what this says.

const val SCHEMA_SQL: String =
    "-- \u2500\u2500\u2500 schema.sql \u2014 one place that knows what the tables are \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n" +
    "--\n" +
    "-- WHY THIS FILE EXISTS\n" +
    "--\n" +
    "-- Until now the schema lived only in database.ts, as a sequence of db.execute()\n" +
    "-- calls mixed with ALTER TABLE migrations. That was fine while there was one\n" +
    "-- implementation. It stops being fine the moment a second one exists, because\n" +
    "-- then there are two schemas that have to agree, and nothing makes them agree\n" +
    "-- except somebody remembering.\n" +
    "--\n" +
    "-- That is the same disease as the two parsers, the two translation systems and\n" +
    "-- the two category detectors: one decision written down in more than one place.\n" +
    "-- The fix is the same each time \u2014 write it once, have everyone read it.\n" +
    "--\n" +
    "-- WHO READS THIS\n" +
    "--\n" +
    "-- It said, for months:\n" +
    "--\n" +
    "--   desktop  loads it at startup and runs the statements in order\n" +
    "--   mobile   hands it to SQLDelight, which compiles typed queries from it\n" +
    "--\n" +
    "-- Neither has ever been true. What actually happens is:\n" +
    "--\n" +
    "--   desktop     builds its database in database.ts, from its own CREATE calls\n" +
    "--   mobile      builds its database from SchemaSql.kt, a constant generated\n" +
    "--               from this file and committed in that repo\n" +
    "--   check-sync  builds throwaway databases from this file to test against\n" +
    "--\n" +
    "-- So the only thing whose real database depends on this file being complete is\n" +
    "-- the phone, and only on a first install. That is the whole explanation for a\n" +
    "-- missing `-- @@` line sitting here for months without anyone noticing: the\n" +
    "-- machine somebody looks at every day never used it.\n" +
    "--\n" +
    "-- WHY THE DESKTOP NEVER STARTED READING IT\n" +
    "--\n" +
    "-- Somebody tried. There was a src/lib/schema.ts with a raw import of\n" +
    "-- shared/schema.sql \u2014 a path outside this repository, so the import could not\n" +
    "-- resolve, so nothing imported it, and the rules in that file sat there being\n" +
    "-- correct and never running while database.ts went on doing it its own way.\n" +
    "-- tombstones.ts still carries the note about it.\n" +
    "--\n" +
    "-- That is why the file now lives in the desktop repository rather than in a\n" +
    "-- folder beside it. Not because the desktop owns the schema \u2014 because a file\n" +
    "-- nobody can import is a file nobody reads, and being neutral bought nothing\n" +
    "-- while costing exactly the thing the file was made for.\n" +
    "--\n" +
    "-- The round that makes the first line true again is database.ts loading this at\n" +
    "-- startup and deleting its own copy of the CREATE statements. It can, now.\n" +
    "--\n" +
    "-- RULES FOR EDITING\n" +
    "--\n" +
    "--   1. Never change an existing CREATE TABLE. Add an ALTER in the migrations\n" +
    "--      section instead. Databases already exist on real machines; a CREATE\n" +
    "--      TABLE IF NOT EXISTS does nothing to them.\n" +
    "--   2. Every statement must be safe to run on every launch. That is what makes\n" +
    "--      \"migrate\" and \"create\" the same code path, which is what stops the two\n" +
    "--      paths drifting.\n" +
    "--   3. Statements are separated by a line containing only `-- @@`. The loaders\n" +
    "--      split on that rather than on semicolons, because triggers contain\n" +
    "--      semicolons inside their bodies.\n" +
    "--\n" +
    "-- WHY `id` STAYS\n" +
    "--\n" +
    "-- Every query and every component uses the local integer id. `uid` is only for\n" +
    "-- talking to other devices. Both exist on purpose; see syncMeta for the long\n" +
    "-- version.\n" +
    "\n" +
    "-- \u2500\u2500\u2500 tasks \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n" +
    "CREATE TABLE IF NOT EXISTS tasks (\n" +
    "  id                   INTEGER PRIMARY KEY AUTOINCREMENT,\n" +
    "  name                 TEXT NOT NULL,\n" +
    "  description          TEXT DEFAULT '',\n" +
    "  category             TEXT DEFAULT 'game',\n" +
    "  reset_type           TEXT NOT NULL,\n" +
    "  reset_time           TEXT,\n" +
    "  reset_day            INTEGER,\n" +
    "  reset_interval_days  INTEGER,\n" +
    "  anchor_date          TEXT,\n" +
    "  event_start          TEXT,\n" +
    "  event_end            TEXT,\n" +
    "  specific_date        TEXT,\n" +
    "  is_priority          INTEGER DEFAULT 0,\n" +
    "  is_urgent            INTEGER DEFAULT 0,\n" +
    "  is_active            INTEGER DEFAULT 1,\n" +
    "  completed_until      TEXT DEFAULT NULL,\n" +
    "  -- WHEN the tick was last touched, which is a different question from how far\n" +
    "  -- it reaches. Sync compares this one, because \"furthest along\" cannot say\n" +
    "  -- \"undo\": clearing the tick produces a value that loses to the old one for\n" +
    "  -- ever. See merge.ts.\n" +
    "  completed_at         TEXT DEFAULT NULL,\n" +
    "  created_at           TEXT DEFAULT (datetime('now'))\n" +
    ");\n" +
    "-- @@\n" +
    "\n" +
    "-- \u2500\u2500\u2500 income \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n" +
    "CREATE TABLE IF NOT EXISTS income (\n" +
    "  id          INTEGER PRIMARY KEY AUTOINCREMENT,\n" +
    "  amount      REAL NOT NULL,\n" +
    "  source      TEXT DEFAULT 'other',\n" +
    "  note        TEXT DEFAULT '',\n" +
    "  date        TEXT NOT NULL,\n" +
    "  created_at  TEXT DEFAULT (datetime('now'))\n" +
    ");\n" +
    "-- @@\n" +
    "\n" +
    "-- \u2500\u2500\u2500 expenses \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n" +
    "CREATE TABLE IF NOT EXISTS expenses (\n" +
    "  id          INTEGER PRIMARY KEY AUTOINCREMENT,\n" +
    "  amount      REAL NOT NULL,\n" +
    "  category    TEXT NOT NULL DEFAULT 'other',\n" +
    "  note        TEXT DEFAULT '',\n" +
    "  date        TEXT NOT NULL,\n" +
    "  created_at  TEXT DEFAULT (datetime('now'))\n" +
    ");\n" +
    "-- @@\n" +
    "\n" +
    "-- \u2500\u2500\u2500 expected_income \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n" +
    "-- Money that should arrive and has not. Not a ledger entry: nothing here has\n" +
    "-- been counted. It becomes an income row only when someone confirms it did.\n" +
    "CREATE TABLE IF NOT EXISTS expected_income (\n" +
    "  id           INTEGER PRIMARY KEY AUTOINCREMENT,\n" +
    "  source       TEXT NOT NULL,\n" +
    "  amount       REAL,\n" +
    "  currency     TEXT NOT NULL DEFAULT 'THB',\n" +
    "  expect_date  TEXT NOT NULL,\n" +
    "  repeat       TEXT,\n" +
    "  note         TEXT NOT NULL DEFAULT '',\n" +
    "  status       TEXT NOT NULL DEFAULT 'waiting',\n" +
    "  created_at   TEXT DEFAULT CURRENT_TIMESTAMP,\n" +
    "  deleted      INTEGER NOT NULL DEFAULT 0\n" +
    ");\n" +
    "-- @@\n" +
    "CREATE INDEX IF NOT EXISTS idx_expected_status ON expected_income(status, expect_date);\n" +
    "-- @@\n" +
    "\n" +
    "-- \u2500\u2500\u2500 budgets \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n" +
    "CREATE TABLE IF NOT EXISTS budgets (\n" +
    "  id            INTEGER PRIMARY KEY AUTOINCREMENT,\n" +
    "  category      TEXT NOT NULL,\n" +
    "  limit_amount  REAL NOT NULL,\n" +
    "  month         TEXT NOT NULL,\n" +
    "  UNIQUE(category, month)\n" +
    ");\n" +
    "-- @@\n" +
    "\n" +
    "-- \u2500\u2500\u2500 saving_goals \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n" +
    "CREATE TABLE IF NOT EXISTS saving_goals (\n" +
    "  id              INTEGER PRIMARY KEY AUTOINCREMENT,\n" +
    "  name            TEXT NOT NULL,\n" +
    "  target_amount   REAL NOT NULL,\n" +
    "  current_amount  REAL NOT NULL DEFAULT 0,\n" +
    "  deadline        TEXT,\n" +
    "  emoji           TEXT DEFAULT '\ud83c\udfaf',\n" +
    "  is_completed    INTEGER DEFAULT 0,\n" +
    "  created_at      TEXT DEFAULT (datetime('now'))\n" +
    ");\n" +
    "-- @@\n" +
    "\n" +
    "-- \u2500\u2500\u2500 app_settings \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n" +
    "-- Key-value. Some keys are device-local (a wallpaper path means nothing on a\n" +
    "-- phone) and some are the same everywhere (currency, language). The split is\n" +
    "-- declared in code, not here, because it is a policy and not a shape.\n" +
    "-- \u2500\u2500\u2500 what actually happened, as opposed to what is true now \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n" +
    "--\n" +
    "-- WHY THIS TABLE EXISTS\n" +
    "--\n" +
    "-- `tasks.completed_until` is one field that gets OVERWRITTEN every cycle, so\n" +
    "-- ticking today erases the trace of yesterday. Nothing anywhere records that a\n" +
    "-- thing was done on a given day. That is not a missing screen, it is missing\n" +
    "-- data, and the days that pass before it is collected are gone for good.\n" +
    "--\n" +
    "-- APPEND ONLY. Nothing here is ever updated or deleted. That makes it the\n" +
    "-- easiest table in the schema to sync \u2014 two devices merging events is a union,\n" +
    "-- with no last-write-wins, no tombstones and no clash rules \u2014 and it makes it\n" +
    "-- the only place that can answer \"what happened on the 14th\" at all.\n" +
    "--\n" +
    "-- WHAT IS DELIBERATELY NOT RECORDED\n" +
    "--\n" +
    "-- Misses. A row per thing not done is a list that is painful to read and\n" +
    "-- trivial to derive later from the schedule if it is ever genuinely wanted.\n" +
    "-- Recording only what happened keeps this a record and stops it becoming a\n" +
    "-- report card. Same reason there are no rates, totals or streaks stored here:\n" +
    "-- storing a score is what makes a score exist.\n" +
    "--\n" +
    "-- SIZE. About 70 bytes a row. Ten ticks a day is roughly 250 KB a year, which\n" +
    "-- is smaller than one photo, so nothing is summarised away and nothing expires.\n" +
    "-- Raw events keep every future question answerable; a summary answers only the\n" +
    "-- question somebody thought of first.\n" +
    "CREATE TABLE IF NOT EXISTS task_events (\n" +
    "  id         INTEGER PRIMARY KEY AUTOINCREMENT,\n" +
    "  -- The task's shared name, not its local row id, so an event still points at\n" +
    "  -- the right task on the other device.\n" +
    "  task_uid   TEXT NOT NULL,\n" +
    "  -- 'done' or 'undone'. Undo is recorded rather than erasing the tick, because\n" +
    "  -- \"ticked then untidied it at 9:02\" is a different afternoon from \"never\n" +
    "  -- ticked\", and only one of them can be reconstructed if the other is dropped.\n" +
    "  kind       TEXT NOT NULL,\n" +
    "  -- When it happened, from the same clock the sync triggers use.\n" +
    "  at         TEXT NOT NULL,\n" +
    "  -- The cycle the tick was for, copied from completed_until at the time. Lets a\n" +
    "  -- calendar say which day's dailies this was, even when the tick was made a\n" +
    "  -- minute before the reset.\n" +
    "  for_cycle  TEXT\n" +
    ");\n" +
    "\n" +
    "-- @@\n" +
    "\n" +
    "-- This separator was missing, and the loader splits on nothing else. Without\n" +
    "-- it the two CREATE TABLE statements above and below arrived as one string,\n" +
    "-- and SQLite runs the first statement in a string and stops. So task_events\n" +
    "-- was created and app_settings silently was not.\n" +
    "--\n" +
    "-- It was invisible for months because no device had ever built this schema\n" +
    "-- from scratch: every phone and every desktop already had app_settings from\n" +
    "-- an earlier version that made it elsewhere. The first fresh install found it\n" +
    "-- immediately, with `no such table: app_settings` on the sync line.\n" +
    "CREATE TABLE IF NOT EXISTS app_settings (\n" +
    "  key    TEXT PRIMARY KEY,\n" +
    "  value  TEXT\n" +
    ");\n" +
    "-- @@\n" +
    "\n" +
    "-- \u2500\u2500\u2500 user_settings \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n" +
    "-- The half of app_settings that describes a person rather than a machine.\n" +
    "--\n" +
    "-- WHY A SECOND TABLE AND NOT A COLUMN OR A KEY PREFIX\n" +
    "--\n" +
    "-- app_settings holds the pairing key and the WebDAV password. Whatever decides\n" +
    "-- which rows may leave this machine has to be right every time, and a predicate\n" +
    "-- over key names is a decision the store, the backup, the migration and both\n" +
    "-- languages would each have to make separately and identically. A table name is\n" +
    "-- a decision the sync layer already knows how to read: SYNC_TABLES lists it or\n" +
    "-- it does not.\n" +
    "--\n" +
    "-- So this is not a split of app_settings so much as a promotion out of it. What\n" +
    "-- stays behind is the machine's own business \u2014 secrets, sync bookkeeping, the\n" +
    "-- wallpaper path \u2014 and none of it is one line of policy away from being sent.\n" +
    "--\n" +
    "-- The shape copies expense_categories on purpose: an autoincrement id so the\n" +
    "-- sync triggers work unchanged, and a UNIQUE key so two devices that invent the\n" +
    "-- same setting independently collide on the natural key and settle, rather than\n" +
    "-- ending up with two rows nobody chose between.\n" +
    "--\n" +
    "-- `key` is the localStorage name, character for character, and `value` is the\n" +
    "-- localStorage string, byte for byte. Not a tidier scheme, deliberately: any\n" +
    "-- translation between the two would be a second format with a second parser on\n" +
    "-- each side, and four parsers that have to agree is the shape of every bug this\n" +
    "-- project has spent a month removing.\n" +
    "CREATE TABLE IF NOT EXISTS user_settings (\n" +
    "  id     INTEGER PRIMARY KEY AUTOINCREMENT,\n" +
    "  key    TEXT NOT NULL UNIQUE,\n" +
    "  value  TEXT\n" +
    ");\n" +
    "-- @@\n" +
    "\n" +
    "-- \u2500\u2500\u2500 expense_categories \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n" +
    "-- User data, not a constant in the source. `label` is nullable and null means\n" +
    "-- \"built-in, translate it\", which keeps the defaults bilingual while letting\n" +
    "-- anything the user makes carry a literal name.\n" +
    "CREATE TABLE IF NOT EXISTS expense_categories (\n" +
    "  id          INTEGER PRIMARY KEY AUTOINCREMENT,\n" +
    "  key         TEXT NOT NULL UNIQUE,\n" +
    "  label       TEXT,\n" +
    "  emoji       TEXT NOT NULL DEFAULT '\ud83d\udce6',\n" +
    "  color       TEXT,\n" +
    "  sort_order  INTEGER NOT NULL DEFAULT 0,\n" +
    "  is_hidden   INTEGER NOT NULL DEFAULT 0\n" +
    ");\n" +
    "-- @@\n" +
    "\n" +
    "-- \u2500\u2500\u2500 migrations \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n" +
    "--\n" +
    "-- Everything below is an ALTER that must survive being run again. SQLite has no\n" +
    "-- ADD COLUMN IF NOT EXISTS, so the loader swallows the \"duplicate column\"\n" +
    "-- error, which is the normal path on every launch after the first.\n" +
    "--\n" +
    "-- Append only. Never edit a line here once it has shipped.\n" +
    "\n" +
    "ALTER TABLE tasks ADD COLUMN specific_date TEXT;\n" +
    "-- @@\n" +
    "ALTER TABLE tasks ADD COLUMN is_priority INTEGER DEFAULT 0;\n" +
    "-- @@\n" +
    "ALTER TABLE tasks ADD COLUMN is_urgent INTEGER DEFAULT 0;\n" +
    "-- @@\n" +
    "ALTER TABLE tasks ADD COLUMN completed_until TEXT DEFAULT NULL;\n" +
    "-- @@\n" +
    "ALTER TABLE tasks ADD COLUMN completed_at TEXT DEFAULT NULL;\n" +
    "-- @@\n" +
    "ALTER TABLE tasks ADD COLUMN notes TEXT DEFAULT '';\n" +
    "-- @@\n" +
    "-- Null = the time floats with the app's zone, which is what every row did\n" +
    "-- before this column existed. A game server resetting at 04:00 Tokyo is pinned;\n" +
    "-- \"take the pills at 09:00\" floats. Null is a choice, not a missing value.\n" +
    "ALTER TABLE tasks ADD COLUMN time_zone TEXT DEFAULT NULL;\n" +
    "-- @@\n" +
    "ALTER TABLE tasks ADD COLUMN intent TEXT DEFAULT NULL;\n" +
    "-- @@\n" +
    "ALTER TABLE tasks ADD COLUMN cycle_checked_until TEXT DEFAULT NULL;\n" +
    "-- @@\n" +
    "ALTER TABLE tasks ADD COLUMN missed_streak INTEGER DEFAULT 0;\n" +
    "-- @@\n" +
    "-- The smallest version of a task that still counts as having done it.\n" +
    "-- \"\u0e25\u0e49\u0e32\u0e07\u0e08\u0e32\u0e19\" is a wall; \"\u0e25\u0e49\u0e32\u0e07\u0e08\u0e32\u0e19 1 \u0e43\u0e1a\" is a doorway. Depression and ordinary\n" +
    "-- procrastination both fail at the same place \u2014 starting \u2014 and shrinking the\n" +
    "-- first step is the standard way through it. Nullable, because most tasks\n" +
    "-- never need one.\n" +
    "ALTER TABLE tasks ADD COLUMN min_step TEXT;\n" +
    "-- @@\n" +
    "ALTER TABLE tasks ADD COLUMN paused_until TEXT DEFAULT NULL;\n" +
    "-- @@\n" +
    "ALTER TABLE tasks ADD COLUMN deleted_at TEXT DEFAULT NULL;\n" +
    "-- @@\n" +
    "-- Which unit the number in `amount` is counted in. Added while these tables\n" +
    "-- held a few hundred rows and there was no sync protocol that would have to be\n" +
    "-- renegotiated, for the same reason the sync columns were: the expensive\n" +
    "-- version of this migration is the one done later.\n" +
    "--\n" +
    "-- Backfilling existing rows as THB is not a guess. Every row that existed was\n" +
    "-- entered when the app could only mean baht.\n" +
    "ALTER TABLE expenses ADD COLUMN currency TEXT NOT NULL DEFAULT 'THB';\n" +
    "-- @@\n" +
    "ALTER TABLE income ADD COLUMN currency TEXT NOT NULL DEFAULT 'THB';\n" +
    "-- @@\n" +
    "-- A limit and a target are amounts, and an amount without a unit is not one.\n" +
    "--\n" +
    "-- These two columns were the last money in the database with no currency\n" +
    "-- beside it, which did not matter while the app could only mean baht and became\n" +
    "-- a silent rewrite the moment it could not: a \u0e3f5,000 food budget read as \$5,000\n" +
    "-- the instant the setting changed, with nothing on screen saying so, and a\n" +
    "-- 30,000 goal likewise. Nothing was converted and nothing was wrong in the row\n" +
    "-- \u2014 the number was simply reinterpreted.\n" +
    "ALTER TABLE budgets ADD COLUMN currency TEXT NOT NULL DEFAULT 'THB';\n" +
    "-- @@\n" +
    "ALTER TABLE saving_goals ADD COLUMN currency TEXT NOT NULL DEFAULT 'THB';\n" +
    "-- @@\n" +
    "-- A bank reference is the one thing on a slip worth keeping: short, opaque, no\n" +
    "-- account numbers or names in it, and it is what makes photographing the same\n" +
    "-- slip twice detectable instead of silently doubling a month's total.\n" +
    "ALTER TABLE expenses ADD COLUMN slip_ref TEXT;\n" +
    "-- @@\n" +
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_expenses_slip_ref\n" +
    "  ON expenses(slip_ref) WHERE slip_ref IS NOT NULL;\n" +
    "-- @@\n" +
    "\n" +
    "-- \u2500\u2500\u2500 sync columns \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n" +
    "--\n" +
    "-- Added last, after every table exists.\n" +
    "--\n" +
    "-- `deleted` on tasks is NEW, and it closes a real hole. The old note said tasks\n" +
    "-- did not need a tombstone because is_active = 0 keeps the row \u2014 true for the\n" +
    "-- bin, false for the button that empties it. purgeTask() ran a real DELETE, so\n" +
    "-- the row vanished carrying no information, and under sync the other device\n" +
    "-- would helpfully send it back. The symptom is \"I deleted it and it came back\",\n" +
    "-- which reads as the machine being haunted.\n" +
    "\n" +
    "ALTER TABLE tasks ADD COLUMN uid TEXT;\n" +
    "-- @@\n" +
    "ALTER TABLE tasks ADD COLUMN updated_at TEXT;\n" +
    "-- @@\n" +
    "ALTER TABLE tasks ADD COLUMN deleted INTEGER NOT NULL DEFAULT 0;\n" +
    "-- @@\n" +
    "ALTER TABLE income ADD COLUMN uid TEXT;\n" +
    "-- @@\n" +
    "ALTER TABLE income ADD COLUMN updated_at TEXT;\n" +
    "-- @@\n" +
    "ALTER TABLE income ADD COLUMN deleted INTEGER NOT NULL DEFAULT 0;\n" +
    "-- @@\n" +
    "ALTER TABLE expenses ADD COLUMN uid TEXT;\n" +
    "-- @@\n" +
    "ALTER TABLE expenses ADD COLUMN updated_at TEXT;\n" +
    "-- @@\n" +
    "ALTER TABLE expenses ADD COLUMN deleted INTEGER NOT NULL DEFAULT 0;\n" +
    "-- @@\n" +
    "ALTER TABLE budgets ADD COLUMN uid TEXT;\n" +
    "-- @@\n" +
    "ALTER TABLE budgets ADD COLUMN updated_at TEXT;\n" +
    "-- @@\n" +
    "ALTER TABLE budgets ADD COLUMN deleted INTEGER NOT NULL DEFAULT 0;\n" +
    "-- @@\n" +
    "ALTER TABLE saving_goals ADD COLUMN uid TEXT;\n" +
    "-- @@\n" +
    "ALTER TABLE saving_goals ADD COLUMN updated_at TEXT;\n" +
    "-- @@\n" +
    "ALTER TABLE saving_goals ADD COLUMN deleted INTEGER NOT NULL DEFAULT 0;\n" +
    "-- @@\n" +
    "ALTER TABLE expense_categories ADD COLUMN uid TEXT;\n" +
    "-- @@\n" +
    "ALTER TABLE expense_categories ADD COLUMN updated_at TEXT;\n" +
    "-- @@\n" +
    "ALTER TABLE expense_categories ADD COLUMN deleted INTEGER NOT NULL DEFAULT 0;\n" +
    "-- @@\n" +
    "ALTER TABLE expected_income ADD COLUMN uid TEXT;\n" +
    "-- @@\n" +
    "ALTER TABLE expected_income ADD COLUMN updated_at TEXT;\n" +
    "-- @@\n" +
    "ALTER TABLE tasks ADD COLUMN notify_before_min INTEGER;\n" +
    "-- @@\n" +
    "-- Allowed to ring through quiet hours, and only at its last call: the final\n" +
    "-- ten-minute warning, or the one reminder when the notice window is that short\n" +
    "-- anyway. Quiet hours otherwise show a reminder without a sound. Set by the\n" +
    "-- person on the task, in advance, the way an alarm is - never inferred from\n" +
    "-- is_urgent, which answers how important a thing is and not whether it is worth\n" +
    "-- waking somebody for. See lib/chime.ts.\n" +
    "ALTER TABLE tasks ADD COLUMN ring_in_quiet INTEGER NOT NULL DEFAULT 0;\n" +
    "-- @@\n"
