// ─── gen-vectors.ts — the desktop implementation, frozen into a spec ─────────
//
// Runs getNextReset() from src/lib/countdown.ts over a matrix of task shapes,
// instants, task zones AND app zones, and records what it answers. The Kotlin
// port must reproduce every value exactly.
//
// WHY app_zone IS AN EXPLICIT FIELD
// A task with time_zone: null floats with whatever the app's zone is, and the
// app's zone defaults to the machine's. So a vector file generated on one
// machine encodes that machine's clock settings as an unstated assumption, and
// every null-zone case silently means something different somewhere else. The
// first draft of this file did exactly that and was wrong by seven hours in 264
// cases. Now every case says which app zone it was generated under, and the
// test sets it explicitly rather than inheriting it.
//
// Run: node -r ./shim.cjs gen.cjs   (after esbuild --bundle)

import { setTimeZonePreference } from "./src/lib/tz";
import { getNextReset } from "./src/lib/countdown";

const realNow = Date.now;
function at<T>(iso: string, fn: () => T): T {
  const fixed = new Date(iso).getTime();
  (Date as any).now = () => fixed;
  try { return fn(); } finally { (Date as any).now = realNow; }
}

/** Instants chosen to land on the edges that break date logic: new year, the
 *  end of February, both US daylight-saving switches, and the evening hours
 *  where the Bangkok date and the UTC date disagree. */
const NOWS = [
  "2026-01-15T03:00:00Z", "2026-01-15T20:30:00Z",
  "2026-02-28T16:59:00Z", "2026-03-01T00:00:00Z",
  "2026-06-30T17:00:00Z", "2026-12-31T16:59:59Z",
  "2026-11-01T08:15:00Z", "2026-08-11T04:00:00Z",
];

/** The zone a task is pinned to. null means it floats with the app's. */
const TASK_ZONES = [null, "Asia/Bangkok", "UTC", "America/New_York", "Australia/Sydney"];

/** What the app's own zone is set to. Two of them, so the floating case is
 *  tested rather than assumed. */
const APP_ZONES = ["Asia/Bangkok", "America/New_York"];

const base = {
  id: 1, uid: "x", name: "t", category: "game", reset_type: "daily",
  reset_time: null, reset_day: null, anchor_date: null, reset_interval_days: null,
  event_start: null, event_end: null, specific_date: null, time_zone: null,
  completed_until: null, notify_before: null, paused_until: null, deleted_at: null,
} as any;

type Case = { id: string; app_zone: string; now: string; task: any; expect: string | null };
const cases: Case[] = [];
let n = 0;

for (const appZone of APP_ZONES) {
  setTimeZonePreference(appZone);

  const push = (now: string, task: any) => {
    const out = at(now, () => getNextReset(task));
    cases.push({
      id: `c${String(++n).padStart(4, "0")}`,
      app_zone: appZone,
      now,
      task,
      expect: out ? out.toISOString() : null,
    });
  };

  for (const now of NOWS) for (const tz of TASK_ZONES) {
    for (const rt of [null, "00:00", "04:00", "23:30", "12:00"])
      push(now, { ...base, reset_type: "daily", reset_time: rt, time_zone: tz });

    for (const d of [0, 1, 3, 6]) for (const rt of [null, "05:00", "21:00"])
      push(now, { ...base, reset_type: "weekly", reset_day: d, reset_time: rt, time_zone: tz });

    for (const anchor of ["2026-01-01", "2025-12-28", "2026-06-15"])
      push(now, { ...base, reset_type: "biweekly", anchor_date: anchor, reset_time: "04:00", time_zone: tz });

    for (const iv of [1, 3, 7, 14, 30, 45]) for (const anchor of ["2026-01-01", "2026-07-04"])
      push(now, { ...base, reset_type: "custom_days", anchor_date: anchor, reset_interval_days: iv, reset_time: "09:00", time_zone: tz });

    for (const end of ["2026-06-30T17:00:00Z", "2026-03-01 10:00:00", "2026-12-31", "2026-12-31T23:59:59Z"])
      push(now, { ...base, reset_type: "event_window", event_end: end, time_zone: tz });

    for (const sd of ["2026-03-08", "2026-11-01", "2027-01-01"]) for (const rt of [null, "14:00"])
      push(now, { ...base, reset_type: "specific_date", specific_date: sd, reset_time: rt, time_zone: tz });

    push(now, { ...base, reset_type: "one_time", event_end: "2026-09-09T12:00:00Z", time_zone: tz });
  }
}

const out = {
  _readme: [
    "Golden vectors for the reset-time engine.",
    "Generated by running the WORKING desktop implementation (src/lib/countdown.ts getNextReset)",
    "over a matrix of task shapes x instants x task zones x app zones.",
    "This file is the specification. The Kotlin port must reproduce every 'expect' exactly.",
    "Per case: set the app zone to 'app_zone', treat 'now' as the current instant, feed 'task'",
    "to nextReset(), compare with 'expect' (ISO-8601 UTC; null means no reset).",
    "Regenerate with scripts/gen-vectors.ts, and only when desktop behaviour changes on purpose.",
  ],
  generated_from: "src/lib/countdown.ts getNextReset()",
  generated_at: "2026-08-11",
  app_zones: APP_ZONES,
  task_zones: TASK_ZONES.map((z) => z ?? "(floats with app)"),
  reset_types: ["daily", "weekly", "biweekly", "custom_days", "event_window", "specific_date", "one_time"],
  count: cases.length,
  cases,
};

require("fs").writeFileSync("schedule-vectors.json", JSON.stringify(out, null, 1));
console.log(cases.length, "cases;", cases.filter(c => c.expect === null).length, "null");
